apiVersion: v1
kind: Secret
metadata:
  name: esppd-jwt
  namespace: esppd
type: Opaque
stringData:
  jwt_private.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_ME
    -----END RSA PRIVATE KEY-----
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_ME
    -----END PUBLIC KEY-----
