apiVersion: v1
kind: Secret
metadata:
  name: esppd-secrets
  namespace: esppd
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
  DATA_ENC_KEY_BASE64: "CHANGE_ME_BASE64_32_BYTES"
